services:

  # back-end api built with golang
  backend:
    container_name: backend
    build: 
      context: abacateiro
      dockerfile: Dockerfile
    ports:
      - "8080:8080"      
    networks:
      - api_network
    depends_on:
      - postgres
    restart: always
    scale: 1 

  # postgres is our primary data store
  postgres:
    container_name: postgres
    build: postgres    
    ports:
      - "5432:5432"
    networks:
      - api_network
    volumes:
      - ./postgres/.docker/postgres_data:/var/lib/postgresql/data
      - ./abacateiro/migrations:/docker-entrypoint-initdb.d/migrations
    environment:
      POSTGRES_USER: abacateiro
      POSTGRES_PASSWORD: abacateiro
      POSTGRES_DB: abacateiro

   # front-end built with quasar 
  frontend:
    container_name: frontend
    build:
      context: ./frontend-abacateiro
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - api_network
    depends_on:
      - backend
    restart: always
    scale: 1
    volumes:
      - ./frontend-abacateiro:/app 

networks:
  api_network:
    driver: bridge

## docker exec -it postgres /docker-entrypoint-initdb.d/at_startup/init.sh
# docker-compose exec postgres 
